service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  sendResponse:
    handler: api/handlers.sendResponse
    events:
      - httpApi:
          path: /api/results
          mehtod: post
          request:
            schemas:
              application/json: ${file(./schemas/sendResponse.json)}
  getResponse:  
    handler: api/handlers.getResponse
    events:  
      - httpApi:
          path: /api/results/{id}
          mehtod: get
