org: fabiomastelari
app: alura-activities
service: api
frameworkVersion: '3'

params:
  default:
    dbName: alura-serverless
    dbTimeout: 5000
  dev:
    connectionString: mongodb://localhost:27017/${self:params.default.dbName}
    salt: K28pc3Ia7ToWO8Ub6Iunq0D1c6NsXuUc
    jwtSecret: Jhgfu3476feihsiiolsdjihjeoodoIUJGHIUIbuBIBiu79248978dfhg86g6734
  prod:

provider:
  name: aws
  runtime: nodejs14.x
  timeout: 10
  tracing:
    lambda: true
  environment:
    MONGODB_CONNECTIONSTRING: ${param:connectionString}
    MONGODB_DB_NAME: ${param:dbName}
    SALT: ${param.salt}
    JWT_SECRET: ${param.jwtSecret}
    MONGODB_TIMEOUT:  ${param.dbTimeout}

functions:
  sendResponse:
    handler: api/handlers.sendResponse
    events:
      - httpApi:
          path: /api/results
          method: post
          request:
            schemas:
              application/json: ${file(./schemas/sendResponse.json)}
  getResponse:  
    handler: api/handlers.getResponse
    events:  
      - httpApi:
          path: /api/results/{id}
          method: get
  login:
    handler: api/handlers.login
    events:
      - httpApi:
          path: /api/login
          method: post
          request:
            schemas:
              application/json: ${file(./schemas/login.json)}
plugins:
  - serverless-offline
