org: fabiomastelari
app: alura-activities
service: api
frameworkVersion: '3'

params:
  default:
    dbName: alura-serverless
  dev:
    connectionString: mongodb://localhost:27017/${self:params.default.dbName}
    salt: K28pc3Ia7ToWO8Ub6Iunq0D1c6NsXuUc
  prod:

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    MONGODB_CONNECTIONSTRING: ${param:connectionString}
    MONGODB_DB_NAME: ${param:dbName}
    SALT: ${param.salt}

functions:
  sendResponse:
    handler: api/handlers.sendResponse
    events:
      - httpApi:
          path: /api/results
          method: post
          request:
            schemas:
              application/json: ${file(./schemas/sendResponse.json)}
  getResponse:  
    handler: api/handlers.getResponse
    events:  
      - httpApi:
          path: /api/results/{id}
          method: get

plugins:
  - serverless-offline
